# Generated by Django 4.2.14 on 2024-07-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="author", field=models.CharField(max_length=100),
        ),
    ]
